### ISSUE TITLE
Angular 9.1 ngcc error

### ISSUE THREAD

**Issue by andreydevua** [mattlewis92/angular-draggable-droppable#104]
When running ngcc command I'm getting this error:
`Error: Error when flattening the source-map "/node_modules/angular-draggable-droppable/bundles/angular-draggable-droppable.umd.js.map" for "/node_modules/angular-draggable-droppable/bundles/angular-draggable-droppable.umd.js": RangeError: Maximum call stack size exceeded`

**Comment by mattlewis92** [comment]
Hey there, this looks like an issue with angular itself and seems to have been fixed in `9.1.1`: https://github.com/angular/angular/commit/56af303
