### ISSUE TITLE
Angular 9 | Circular source file mapping dependency

### ISSUE THREAD

**Issue by GlauberF** [mattlewis92/angular-draggable-droppable#107]
Warning: Unable to fully load /var/www/html/pwa-vimbo-new/node_modules/angular-draggable-droppable/bundles/angular-draggable-droppable.umd.js for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa-vimbo-new/node_modules/angular-draggable-droppable/bundles/angular-draggable-droppable.umd.js.map -> /var/www/html/pwa-vimbo-new/node_modules/angular-draggable-droppable/bundles/angular-draggable-droppable.umd.js.map

**Comment by mattlewis92** [comment]
Please see https://github.com/mattlewis92/angular-draggable-droppable/issues/105#issuecomment-612595666, thanks!
