### ISSUE TITLE
No provider for DraggableHelper!

### ISSUE THREAD

**Issue by OlivierAumon** [mattlewis92/angular-draggable-droppable#11]
Hi!

I try to use your work but when I copy your code I get this error in my browser's console.

Any ideas why I get it?

**Comment by mattlewis92** [comment]
As documented in the [change log](https://github.com/mattlewis92/angular-draggable-droppable/blob/master/CHANGELOG.md), you need to import the module like `DragAndDropModule.forRoot()` instead of `DragAndDropModule`. Hope that helps!
