### ISSUE TITLE
this.renderer.setStyle is not a function

### ISSUE THREAD

**Issue by MadEddieFFS** [mattlewis92/angular-draggable-droppable#12]
![dragdrop](https://cloud.githubusercontent.com/assets/4107761/24544457/3f6f148e-15fb-11e7-8323-4be613dbf204.gif)

I am importing the module with DragAndDropModule.forRoot()

The HTML is
```
<ul class="list divider-full-bleed list-events">
			<li class="tile" 
            *ngFor="let event of draggableEvents"
            mwlDraggable
            [dropData]="{event: event}"
            style="position:relative; z-index: 10">
             <div class="tile-content">
					<div class="tile-text">{{event.title}}</div>
					<div class="tile-icon"><i class="fa fa-circle-thin" [style.color]="event.color.primary"></i></div>
				</div>
          </li>
```

and the event in the component as:
 ```
draggableEvents: CalendarEvent[] = [{
    title: 'Available',
    draggable: true,
    start: new Date(),
    color: this.colours.green
  },
  {
    title: 'UnAvailable',
    draggable: true,
    start: new Date(),
    color: this.colours.red
  }
  ];
```

**Comment by mattlewis92** [comment]
What version of angular are you using?

**Comment by MadEddieFFS** [comment]
"@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.1",
    "@angular/compiler": "^4.0.1",
    "@angular/compiler-cli": "^4.0.1",
    "@angular/core": "^4.0.1",
    "@angular/forms": "^4.0.1",
    "@angular/http": "^4.0.1",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^4.0.1",
    "@angular/platform-server": "^4.0.1",
    "@angular/router": "^4.0.1",
    "rxjs": "^5.1.0",
    "typescript": "^2.2.2",
    "zone.js": "^0.8.5"

**Comment by MadEddieFFS** [comment]
Sorry - the issue has gone away now. It seem other components on the page may well have been causing issues rather than this one
