### ISSUE TITLE
Include original event in event subscriptions?

### ISSUE THREAD

**Issue by mtr** [mattlewis92/angular-draggable-droppable#15]
Dear Matt Lewis,

Thank you for your great work on this module.

Could you please consider including the original/browser events in the `onDrag`, `onDragOver`, `onDrop`, etc. events?  The way I understand the documentation and code, currently I can only access the `dropData` in the `mwlDroppable`'s `onDrop` handler.  It would be great if that `$event` also contained the original browser event, like in `{dropData: …, event: …}`.  

The reason I need this is that I have created a “huge” (13 x 13) grid where each cell is a droppable, but it slows down the performance considerably.  If I had access to the drag/drop event's coordinates, I could calculate which cell is hovered and dropped upon, and I would only need to make one element (the whole grid) droppable.

**Comment by mattlewis92** [comment]
hmm that's odd, I've put a lot of effort into making this lib as performant as possible, I would expect it to be able to cope with 169 droppable squares quite easily. I'll do some profiling and see if I can see what's causing the slowdown. What browser are you seeing the perf issues in?

**Comment by mtr** [comment]
It's quite performant in desktop Chrome, but starts to show small “lag” effects in mobile browsers on Android and iOS.

**Comment by mtr** [comment]
@mattlewis92: I've sent you an email with a video that should explain the usage context better.  If the draging and dropping were the only things going on, the performance would probably not be a problem.

**Comment by mattlewis92** [comment]
Sorry about the late reply on this, been super busy lately with work + real life, and open source hasn't been at the top of my list. Do you still need this? 😄

**Comment by mtr** [comment]
Hi, @mattlewis92.  No problem.  I know how it is when work and real life team up and demand that you spend time on them.  :smile:  For now, I've made some other optimizations, like changing the cell components' `changeDetection` to `ChangeDetectionStrategy.OnPush`, and it *might* do the trick for now, by reducing the number of actual change-detection checks performed for each relevant event.

So, until I gain more experience with the choices I've made, I do not *need* this feature, but I would love to be able to compare the performance differences of the approaches (if any).  However, if I feel that this issue becomes pressing again, I can either make the changes myself and propose a pull request, or I can ask you politely if you would like to reopen this issue.  :wink:

**Comment by mattlewis92** [comment]
Ah yeah, using OnPush is a really good way of getting a nice perf boost, have a look at [this article](https://blog.thoughtram.io/angular/2017/02/02/making-your-angular-app-fast.html) as well, as it might give you some additional ideas on how to make things faster. I only wrote this module as I needed snap grids when dragging, if you don't need that feature which it didn't look like from the video you sent me, then your best bet is probably just to use [native drag and drop](https://www.w3schools.com/html/html5_draganddrop.asp) as that will probably give you the best performance as it's baked into the browsers API. I will close this issue for now then 😄
