### ISSUE TITLE
angular/forms api support

### ISSUE THREAD

**Issue by nayfin** [mattlewis92/angular-draggable-droppable#18]
Sorry, this is more of a question than an issue. Does this now or are there plans to support dragging/dropping form components? I need to allow users to reorder a formArray and am trying to find a library that can do this natively.

**Comment by mattlewis92** [comment]
It sounds like you want a sortable component, rather than a drag and drop component. I would recommend something like this: https://github.com/SortableJS/angular-sortablejs

Hope that helps! 😀

**Comment by nayfin** [comment]
Thank you! That helped immensely.
