### ISSUE TITLE
Drag with page zoomed

### ISSUE THREAD

**Issue by abnersouza** [mattlewis92/angular-draggable-droppable#19]
Hi,

First would like to thank you guys for the awesome work put on this draggable-droppable.

I would like to ask if you guys can think anyway to overcome an issue i'm having, basically I have a component similar to a page, where you can add controls inside. Then you should be able to move the controls around. In that component I have a zoom, where the user can zoom in and zoom out, what the zoom is doing is set the css property zoom using percentage. When the page is zoomed and i drag and move, the mouse is more sensitive so the control moves fast and lost the mouse cursor, If I move really slow it kinda works ok, but if you try to move in a normal speed, it really gets hard to use it.

For you be able to reproduce, just open your demo https://mattlewis92.github.io/angular-draggable-droppable/demo/ and add a css zoom: 200% to the div with id="demo".

<img width="1276" alt="zoom" src="https://user-images.githubusercontent.com/3270632/31583897-0657d42e-b182-11e7-87b0-9724ad0068f9.png">

I found a similar issue using Jquery Draggable, the guy manage to fix it. https://stackoverflow.com/questions/2930092/jquery-draggable-with-zoom-problem

Please let me know,

Thanks a lot.

Abner

**Comment by mattlewis92** [comment]
One way to get around this could be to set `ghostDragEnabled=[false]` and then implement the logic yourself for moving the element around that respects the zoom property.
