### ISSUE TITLE
Blur event not working

### ISSUE THREAD

**Issue by abnersouza** [mattlewis92/angular-draggable-droppable#20]
Hi,

Is there anyway to have a blur event while using the mwlDraggable? I have a input using both mwlDraggable and mwlResizable, if i have only the mwlResizable the blur event works, but when i have mwlDraggable it does not.

Thanks

**Comment by mattlewis92** [comment]
This will be fixed in 2.0 by the behaviour change that only prevents default on the element if its actually dragged. Thanks for reporting! 😄
