### ISSUE TITLE
Click event begins drag

### ISSUE THREAD

**Issue by alex7egli** [mattlewis92/angular-draggable-droppable#21]
Just clicking (left or right) on an element with mwlDraggable directive triggers dragBegin event.

**Comment by alex7egli** [comment]
dragging can be used instead to detect actually drag begin, so this is definitely low importance, assuming it is not already the intended functionality.

**Comment by mattlewis92** [comment]
Thanks for reporting this, I double checked how native drag and drop works and it's the same way, I will cut a 2.0 release shortly with the fix. It also fixes quite a few other issues along the way 😄
