### ISSUE TITLE
If I scroll the screen while dragging an mwlDraggable element and then drop it on an mwlDroppable element the drop is not registered

### ISSUE THREAD

**Issue by alex7egli** [mattlewis92/angular-draggable-droppable#23]
If I have an mwlDraggable element on a screen that can scroll, if I drag it and scroll the screen with my mouse wheel while dragging and then drop it on an mwlDroppable element that I've scrolled to the drop event does not happen and it is treated as if I dropped the element on dead space, it just ends the drag. Expected behaviour is if I drop an mwlDraggable element on an mwlDroppable element then the drop action always happens, regardless of how much the screen scrolled during the drag.

**Comment by mattlewis92** [comment]
Thanks for reporting, will be fixed in the next release! 😄

**Comment by komalkedia** [comment]
It is still not fixed, I m still facing issue. Not able to drop on droppable element after scrolling.
