### ISSUE TITLE
drag & drop between container with overflow scroll or hidden

### ISSUE THREAD

**Issue by volser** [mattlewis92/angular-draggable-droppable#25]
currently dragging element not visible
http://recordit.co/vKjUsWIqyo

possible solution is to create shadow element in body
(like you did here clonedNode  https://github.com/mattlewis92/angular-resizable-element/blob/master/src/resizable.directive.ts)

**Comment by volser** [comment]
why you didn't use html5 d&d?

**Comment by mattlewis92** [comment]
Ah damn, that's annoying, yeah I think you're right, the only way to get around this is by making the element absolute and removing it from the document flow as you drag the element. Would you like to make a pull request?

My reasoning for not using html5 drag and drop was because I needed support for snap grids which isn't possible with native drag and drop.

**Comment by Nightbr** [comment]
hey, same problem here any news on this?

**Comment by rosinako** [comment]
Is there a solution for this?

**Comment by levu74** [comment]
I saw the cloned node solution. the cloned node is added by parent node. In case, the item is dragged across components then the drag image is still hidden. How about if the ghost element is placed in body tag. Does it violate Angular application?

**Comment by justin-sleep** [comment]
If it helps anyone, this is how I worked around this.

```

**Comment by justin-sleep** [comment]
If it helps anyone, this is how I worked around this:

### component.html
```typescript
<li 
    *ngFor="let drill of skill.drills"
    id="drill-{{drill.info.id}}"
    mwlDraggable
    [dropData]="{event: drill.event}"
    (click)="drillInfo(drillinfo,drill.info)"
    class="dropclass"
    (dragStart)="startDragging('drill-' + drill.info.id)"
    (dragEnd)="endDragging('drill-' + drill.info.id)"
    [style.background]="skill.color">
    {{ drill.title }}
</li>
```
### component.ts
```typescript
  startDragging(drillTag) {
    let drill = document.getElementById(drillTag);
    let domRect = drill.getBoundingClientRect();
    drill.style.position = 'fixed';
    drill.style.top = domRect.top + 'px';
    drill.style.left = domRect.left + 'px';
  }

  endDragging(drillTag) {
    let drill = document.getElementById(drillTag);
    drill.style.position = 'relative';
    drill.style.top = 'unset';
    drill.style.left = 'unset';
  }
```

While dragging, the position is fixed and aligned to its original viewport position.  After dragging, we make it relative again and unset the `top` and `left` properties.

**Comment by mattlewis92** [comment]
Thanks for the pointer @justin-sleep, I've combined that with the solution suggested by @volser. I'm going to do a bit more testing with it before pushing it to npm to everyone. You can try it out in the meantime with:
```
npm i angular-draggable-droppable@alpha
```

Please let me know if there are any problems 😄
