### ISSUE TITLE
DnD is not working

### ISSUE THREAD

**Issue by harishrohokale** [mattlewis92/angular-draggable-droppable#26]
I have imported module properly and used below code in my app. Still it gives me below error:
```
Can't bind to 'dragSnapGrid' since it isn't a known property of 'div
```
Which means module is not imported properly?

Can you help me on this?

**Comment by mattlewis92** [comment]
It sounds like you're not adding the `mwlDraggable` property to the element you're trying to drag, however it's hard to say for sure without any code. Happy to help debug more if you can share some code that isn't working for you! 😄

**Comment by harishrohokale** [comment]
@mattlewis92 I have used the code snippet which you have added:
```
<div mwlDraggable (dragEnd)="dragEnd($event)">Drag me!</div>
    <div
      mwlDroppable
      (drop)="this.droppedData = $event.dropData">
      <span [hidden]="droppedData">Drop here</span>
      <span [hidden]="!droppedData">Item dropped here with data: "{{ droppedData }}"!</span>
    </div>
```

and its corrosponding TS code

**Comment by mattlewis92** [comment]
I can't see `dragSnapGrid` being used in that snippet which would cause the error you're experiencing. Can you make something runnable on plunker or stackblitz etc?
