### ISSUE TITLE
Drop Data Casting

### ISSUE THREAD

**Issue by daneshmandi** [mattlewis92/angular-draggable-droppable#27]
Hello,

I have a difficulty to cast dropData to its original object type. In may case I have a object of a custom class called Task and I bound the DropData to Task object like: 

`<div *ngFor="let task of software.Tasks">
                <div mwlDraggable
                     dropData="{{task}}">
                  <h4> {{task.Name}}</h4>
                </div>`

and my drop event look like this:

`OnDrop({ dropData }: { dropData: any })
  {

}`

In this event I would like to cast back the dropData to Task but it doesn't work. I tried the following casting but none worked:

`const task = <Task> dropData;`

`const task = dropData as Task;`

as I dropData it show as "[object Object]"

Would you please helm me with this?

Thanks in advanced!

**Comment by daneshmandi** [comment]
I found a way finally but not sure it is the best way though. I can use json pipe when binding dropData like:
`<div *ngFor="let task of software.Tasks"> <div mwlDraggable dropData="{{task | json}}"> <h4> {{task.Name}}</h4> </div>`

**Comment by mattlewis92** [comment]
You can just bind the drop data using the square brackets notation:
```
<div mwlDraggable [dropData]="task">
```

**Comment by daneshmandi** [comment]
Perfect! Thanks

**Comment by daneshmandi** [comment]
Perfect! Thanks.
