### ISSUE TITLE
IE11 & Firefox (59.0.2) - Highlighting of text while dragging (before and after drop)

### ISSUE THREAD

**Issue by grdthato** [mattlewis92/angular-draggable-droppable#28]
While dragging an element that contains text to the drop area, if you pass over an area that contains text it will become and stay highlighted in IE & Firefox. This was replicated with your demo site. Any way to fix this behavior?

**Comment by temp5** [comment]
Fixed in https://github.com/mattlewis92/angular-calendar/pull/521

**Comment by mattlewis92** [comment]
With safari it's required to apply `user-select: none` to all document elements in order for it to work which is a pain to implement manually, so I've baked the into the package so it all works out the box. You can try it out with:
```
npm i angular-draggable-droppable@alpha
```
