### ISSUE TITLE
Any plan or timeframe to upgrade to angular 6 better say RxJS 6 ? 

### ISSUE THREAD

**Issue by daneshmandi** [mattlewis92/angular-draggable-droppable#31]

**Comment by mattlewis92** [comment]
I'll work on it in the next few days, in the meantime you can do 
```
npm i rxjs-compat
```

to get it working.

**Comment by mattlewis92** [comment]
I've just cut `3.0.0` which supports angular / rxjs 6+. LMK if you have any problems 😄

**Comment by daneshmandi** [comment]
@mattlewis92 Thanks for the quick fix!
