### ISSUE TITLE
ERROR TypeError: "Object(...) is not a function"

### ISSUE THREAD

**Issue by anurag-arora** [mattlewis92/angular-draggable-droppable#35]
Environment
Angular CLI: 1.7.4
Node: 10.0.0
OS: linux x64
Angular: 5.2.11

**Comment by mattlewis92** [comment]
This module is only compatible with angular >= 6.0.0

**Comment by anurag-arora** [comment]
can you suggest me some other module using which I can add a draggable feature in Tables

**Comment by mattlewis92** [comment]
This one is pretty decent: https://github.com/ObaidUrRehman/ng-drag-drop

**Comment by anurag-arora** [comment]
Thanks a lot.
