### ISSUE TITLE
Delay drag

### ISSUE THREAD

**Issue by rosostolato** [mattlewis92/angular-draggable-droppable#39]
**Is your feature request related to a problem? Please describe**
No.

**Describe the solution you'd like**
I would like to delay the drag. 

**Describe your use case for implementing this feature**
On user click, it should wait 3 seconds before start dragging or it will cancel if user moves de mouse before the timeout.

**Additional context**
I need this because i'm developing on mobile and my drags are in a overflow-y list and it's causing some bugs. I don't know if it's already implemented, sorry if it is already in.

**Comment by mattlewis92** [comment]
I think you can use the cancelDrag feature for this. Logic would be:
* User presses the mouse down, listen for `dragPointerDown` event and log time
* On `dragStart`, check if current time minus previous logged time is < 3 seconds, if so cancel the drag like this: https://github.com/mattlewis92/angular-draggable-droppable/blob/master/test/draggable.directive.spec.ts#L650-L679

Hope that helps! 😄

**Comment by mattlewis92** [comment]
Ah, I only added it in the latest beta, make sure you're on `4.0.0-beta.7`

**Comment by rosostolato** [comment]
You're awesome man! I love your codes rsrs... Angular-calendar is another awesome project.

**Comment by rosostolato** [comment]
Just for your known: cancelDrag didn't work as it should be. It's like the ghost element was created, then it turned to a static element and this is causing a bug on my project. My solution was using `validateDrag` that prevents the drag start for real.
![ghost element](https://user-images.githubusercontent.com/27731641/41998993-8d1f9202-7a32-11e8-8c28-6b30b340c737.jpg)
