### ISSUE TITLE
Unable to preventDefault

### ISSUE THREAD

**Issue by rosostolato** [mattlewis92/angular-draggable-droppable#40]
**Describe the bug**
On mobile, it's logging error to console while you are dragging with touch. For each move, it pushes one more error:

> [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

The bug is on line `angular-draggable-droppable.js:93`
`pointerMoveEvent.event.preventDefault();`

**Minimal reproduction of the problem with instructions**
Using google chrome mobile emulation: Enable mwlDraggable and drag with touch.

**Screenshots**
![capture](https://user-images.githubusercontent.com/27731641/41942792-471aebdc-7977-11e8-8dba-4ac12495c79d.JPG)

**Versions**

- `@angular/core`:
- `angular-draggable-droppable`:
- Google Chrome lastest version:

**Comment by mattlewis92** [comment]
This is already removed in the latest beta, if you do `npm i angular-draggable-droppable@beta` it should be gone.
