### ISSUE TITLE
StaticInjectorError on prodution

### ISSUE THREAD

**Issue by rosostolato** [mattlewis92/angular-draggable-droppable#41]
**Describe the bug**
I'm getting this error on prodution mode on my project. I tried removing all dependencies but the error continued. When I downgraded angular-draggable-droppable, that error went away. So my conclusion is that there is a problem with angular-draggable-droppable module.
Maybe this commit is the problem: [https://github.com/mattlewis92/angular-draggable-droppable/commit/5ae52a7046275dff57c1bdb5600f0b120e8c2c36](url)

**Minimal reproduction of the problem with instructions**
Build or serve a project on prodution mode. On develepment mode there is no errors.

**Screenshots**
![error](https://user-images.githubusercontent.com/27731641/42037905-e05785fa-7abf-11e8-85ad-dabd80ebd874.JPG)

**Versions**

- `@angular/core`: `6.0.8`:
- `angular-draggable-droppable`: `^4.0.0-beta.9`:
- Chrome lastest version:

**Comment by csigritz** [comment]
Did you remove the `DraggableHelper` from the providers section in your `app.module.ts`? I'm quite sure, that was needed in older versions...

**Comment by rosostolato** [comment]
This is my `app.module.ts`:
```
// Angular Core
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

// Material and Bootstrap
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { MatListModule } from '@angular/material/list';

// Others Modules
import { PapaParseModule } from 'ngx-papaparse';
import { NgxFilequakeModule } from '@ebcoder/ngx-filequake';
import { DragAndDropModule } from 'angular-draggable-droppable';
import { AngularFontAwesomeModule } from 'angular-font-awesome';

// Components
import { AppComponent } from './app.component';
import { PeriodTableComponent } from './period-table/period-table.component';
import { MateriasTableComponent } from './materias-table/materias-table.component';
import { ClickEffectDirective } from './materias-table/clickEffect/click-effect.directive';
import { SidebarComponent } from './sidebar/sidebar.component';

@NgModule({
  declarations: [
    AppComponent,
    PeriodTableComponent,
    MateriasTableComponent,
    ClickEffectDirective,
    SidebarComponent
  ],
  imports: [
    MatListModule,
    BrowserModule,
    PapaParseModule,
    DragAndDropModule,
    NgxFilequakeModule,
    NgbModule.forRoot(),
    AngularFontAwesomeModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by csigritz** [comment]
Looks fine... then my guess was wrong... Sorry.

**Comment by mattlewis92** [comment]
What does 
```
npm ls angular-draggable-droppable
```

output?

**Comment by rosostolato** [comment]
`-- angular-draggable-droppable@4.0.0-beta.12`

After upgrading to beta.12, the error is different:
![error](https://user-images.githubusercontent.com/27731641/42061352-389f2c96-7b00-11e8-85ab-b9b929dbde8c.JPG)

**Comment by rosostolato** [comment]
ng compiler thrown this warning:
```
WARNING in ./src/app/period-table/period-table.component.ngfactory.js
64:278-283 "export 'ɵc' (imported as 'i5') was not found in 'angular-draggable-droppable'

WARNING in ./src/app/period-table/period-table.component.ngfactory.js
64:314-319 "export 'ɵd' (imported as 'i5') was not found in 'angular-draggable-droppable'

WARNING in ./src/app/materias-table/materias-table.component.ngfactory.js
65:300-305 "export 'ɵc' (imported as 'i9') was not found in 'angular-draggable-droppable'
```

**Comment by rosostolato** [comment]
This is my project on github, you can clone it for testing if you wish: [https://github.com/rosostolato/blackboard](url)

**Comment by rosostolato** [comment]
I downgraded to `angular-draggable-droppable@4.0.0-alpha.8` that is the version of my last successful build. I served on develepment mode, I did not used `forRoot()` on imports and I got a similar error:

![error](https://user-images.githubusercontent.com/27731641/42062618-7cc8eed0-7b04-11e8-9ec1-355907700941.JPG)

**Comment by mattlewis92** [comment]
hmm, that's super weird, I'm using this in our app with AoT as well and I'm not getting these errors. I will debug more later when I've got some free time 😄

**Comment by mattlewis92** [comment]
I checked out your repo and it ran fine for me with AoT (`npm run build -- --configuration=production`) and there were no run time errors when serving the app. It might be an issue with npm. Give this a try:
```
npm i -g npm
rm -rf node_modules
npm install
```

**Comment by naakaah** [comment]
I got the same error and @mattlewis92 's fix worked for me 👍
