### ISSUE TITLE
Can't import DropEvent in project

### ISSUE THREAD

**Issue by naakaah** [mattlewis92/angular-draggable-droppable#42]
**Describe the bug**

I can't import the DropEvent interface into my project as it's not exported in the definition file (droppable.directive.d.ts)

**Minimal reproduction of the problem with instructions**

Try to import DropEvent in your component

**Screenshots**

None

**Versions**

- `@angular/core`: ^6.0.7
- `angular-draggable-droppable`: 3.0.1
- Browser name and version: Chrome 67.0.3396.99

**Comment by mattlewis92** [comment]
This should be fixed in the latest beta, if you upgrade via `npm i angular-draggable-droppable@beta` it should be available.
