### ISSUE TITLE
Too many style element created into the DOM

### ISSUE THREAD

**Issue by naakaah** [mattlewis92/angular-draggable-droppable#44]
**Describe the bug**
When a lot of Draggable elements are present on the page, every time we drag the element, a <style> element is added into the <head> element.
The issue is that it's make debugging CSS in Chrome DevTools really difficult.
I guess it's a side effect of issue #28 

**Minimal reproduction of the problem with instructions**
See bug description

**Screenshots**
![image](https://user-images.githubusercontent.com/10684049/43085867-56620fa0-8e9c-11e8-9ac0-5f97503be4ef.png)

**Versions**

- `@angular/core`: latest
- `angular-draggable-droppable`: @beta
- Browser name and version: Chrome (latest)

**Comment by naakaah** [comment]
I didn't mention also the fact that this disables text selection on all application, not draggable items only.
I want my users to be able to select text on page.
I think these CSS attributes should be implemented by the user on it's own CSS class

**Comment by mattlewis92** [comment]
huh, that's odd, this should only be added whilst you're dragging an item, and it [should be removed](https://github.com/mattlewis92/angular-draggable-droppable/blob/master/src/draggable.directive.ts#L406) after dragging. Is it still present after you've dropped an item?

**Comment by naakaah** [comment]
You're right! The style element is added when dragging the item and removes it when dragging ends.
However, if I only click on the draggable item without moving it, it will add the style element but not remove it on mouseup event.

**Comment by mattlewis92** [comment]
Ah yes, nice spot! I've just published a new beta with a fix.

`dragStart` / `dragEnd` should only ever be called after the element was moved at least once, there are test to verify this is the case: https://github.com/mattlewis92/angular-draggable-droppable/blob/master/test/draggable.directive.spec.ts#L603-L612
