### ISSUE TITLE
Dragging a mwlDraggable in a child component to a mwlDroppable in the parent component 

### ISSUE THREAD

**Issue by chimingho** [mattlewis92/angular-draggable-droppable#46]
A mwlDraggable element becomes invisible when dragging out of child component area. However, continuing dropping it into a mwlDroppable element in parent component still triggers event properly. I look though codes and only find some tests related to draggableElement.style.visibility, but can not get any clues what makes mwlDraggable invisible. 

**Minimal reproduction of the problem with instructions**
use your sample at https://github.com/mattlewis92/angular-draggable-droppable, and move mwlDraggable part into a child component.

I try to reproduce the issue at stackblitz, but get an DraggableHelper error I don't know how to resolve. Below is the link.
https://stackblitz.com/edit/angular-ezewis?file=src%2Fapp%2Fhello.component.ts

![image](https://user-images.githubusercontent.com/7513628/43165342-ab3e992e-8f61-11e8-89ef-39e9ea5152c5.png)
![image](https://user-images.githubusercontent.com/7513628/43165505-0ba78c1c-8f62-11e8-8974-c22f21a4571b.png)

**Screenshots**

**Versions**

- `@angular/core`:  "^6.0.5",
- `angular-draggable-droppable`: "^3.0.1",
- Browser name and version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Hey there, the error you're experiencing is caused by the docs being for the current beta, if you add `DragAndDropModule.forRoot()` to your example it starts running. Please can you go ahead and update your stackblitz? Thanks!

**Comment by mvaljento** [comment]
@chimingho, Was this issue ever resolved for you?
