### ISSUE TITLE
Drag handle

### ISSUE THREAD

**Issue by AndreeaCascaval** [mattlewis92/angular-draggable-droppable#50]
**Is your feature request related to a problem? Please describe**

I am implementing a list of draggable items and for responsive purposes, I would like to have just an Icon that is triggering the drag, but the drag & drop visual animation to remain on the draggable item.

In responsive design, in a list, you must be able to scroll freely without triggering drag &drop, the most common UX solution is the "drag handle" on a specific area inside the draggable item

**Additional context**

**Comment by mattlewis92** [comment]
This sounds reasonable, I'd be happy to accept a PR that adds this functionality. You could copy the implementation from [here](https://github.com/mattlewis92/angular-resizable-element/blob/master/src/resize-handle.directive.ts)
