### ISSUE TITLE
Draggable item append to body

### ISSUE THREAD

**Issue by laijuthomas** [mattlewis92/angular-draggable-droppable#51]
**Is your feature request related to a problem? Please describe**
When I add the draggable element inside a div with overflow auto and when I drag the element over the screen, the element gets hidden by the overflow of the div.

**Describe the solution you'd like**
I am using the draggable element inside ngx-perfect-scrollbar container

**Describe your use case for implementing this feature**

I have a static positioned div in which I have few elements which I need to drag to another div outside the static position div
**Additional context**

**Comment by mattlewis92** [comment]
This should be fixed in the latest beta!

```
npm i angular-draggable-droppable@beta
```

Please let me know if you find any issues ✌️

**Comment by laijuthomas** [comment]
This is fixed now. Thank you.
