### ISSUE TITLE
dragActiveClass and dragOverClass

### ISSUE THREAD

**Issue by g1bbzy** [mattlewis92/angular-draggable-droppable#53]
**Describe the bug**

classes given to dragActiveClass and dragOverClass attribute are not being applied when the event occur.

**Screenshots**

**Versions**

- `@angular/core`:  6.0.7
- `angular-draggable-droppable`: 3.0.1
- Browser name and version: Chrome 67.0.3396.99

**Comment by mattlewis92** [comment]
These options are only available in the latest beta, you can upgrade to it here:
```
npm i angular-draggable-droppable@beta
```

Please let me know if you hit any problems!

**Comment by g1bbzy** [comment]
Thanks mate. Ill give it a go.

**Comment by mattlewis92** [comment]
This behaviour should be the same, there's a test to [verify](https://github.com/mattlewis92/angular-draggable-droppable/blob/master/test/draggable.directive.spec.ts#L603-L612) this. 

To increase the drag threshold some more you can use the `validateDrag` input and pass a function like this:
```
function dragThresholdValidator({ x, y }) {
  const MIN_DRAG_THRESHOLD = 3;
  return Math.abs(x) > MIN_DRAG_THRESHOLD || Math.abs(y) > MIN_DRAG_THRESHOLD;
}
```

**Comment by yogibimbi** [comment]
Cool. I was getting another issue, namely getting the error

`ERROR Error: StaticInjectorError(AppModule)[DraggableDirective -> DraggableHelper]: 
StaticInjectorError(Platform: core)[DraggableDirective -> DraggableHelper]: 
NullInjectorError: No provider for DraggableHelper! `

as soon as I invoked the mwlDraggable directive on any HTML tag. Importing the module .forRoot() took care of that (lots and lots of trial and error, and our library structure is a bit, let's say, complex), but that is not necessary anymore. Now, if I could get rid of the "@beta" thingie for the install, that would put probably minds at ease in management (if they knew...).
