### ISSUE TITLE
dragOverClass input

### ISSUE THREAD

**Issue by clogeceyhan** [mattlewis92/angular-draggable-droppable#55]
**Describe the bug**

dragOverClass input is not included in the source. I see it in the demo but after I've installed the project, it does not have it.

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

**Comment by mattlewis92** [comment]
This is only available in the 4.x beta's
```
npm i angular-draggable-droppable@beta
```

Hope that helps! 😄
