### ISSUE TITLE
Current build has renderer calls stripped out so drag classes are not working

### ISSUE THREAD

**Issue by admosity** [mattlewis92/angular-draggable-droppable#56]
**Describe the bug**

Dev console:
![image](https://user-images.githubusercontent.com/4655972/44098472-4ba32c84-9fae-11e8-9a22-9174fefa937e.png)

There should be a renderer call here:
https://github.com/mattlewis92/angular-draggable-droppable/blob/master/projects/angular-draggable-droppable/src/lib/droppable.directive.ts#L149-L152

Diving into the build has the same issue:
![image](https://user-images.githubusercontent.com/4655972/44098809-20c6803c-9faf-11e8-8e86-053b0b54daca.png)

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-tubww6?file=src%2Fapp%2Fapp.component.html

**Screenshots**

![aug-14-2018 10-51-11](https://user-images.githubusercontent.com/4655972/44099157-fe997cd4-9faf-11e8-8107-e6c9c1e2ffe9.gif)

**Versions**

- `@angular/core`: 6.1.2
- `angular-draggable-droppable`: 3.0.1
- Browser name and version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by admosity** [comment]
@mattlewis92  Looks like you introduced the drag classes recently. Will you be dropping a release soon?

**Comment by mattlewis92** [comment]
Sorry for the confusion, what's on master is 4.x, if you do
```
npm i angular-draggable-droppable@beta
```

It should fix all your issues, the plan is to release 4.x final once https://github.com/mattlewis92/angular-draggable-droppable/issues/50 is done

**Comment by admosity** [comment]
Yep, I just went with

```html
<div class="mmds-c-page__dropzone"
  mwlDroppable [class.mmds-c-page__dropzone--active]="bottom.active"
  #bottom (dragEnter)="bottom.active = true"
  (dragLeave)="bottom.active = false"
  (drop)="bottom.active = false; _addBottom( $event.dropData )">

</div>
```

in the meanwhile...
