### ISSUE TITLE
NullInjectorError: No provider for DraggableHelper

### ISSUE THREAD

**Issue by 2easy2pay** [mattlewis92/angular-draggable-droppable#63]
I had implemented editable/deletable events calendar .Everything works fine with development environment,once i deploy the project with angular-cli getting error as follows,

ERROR Error: StaticInjectorError(AppModule)[DraggableDirective -> DraggableHelper]:
StaticInjectorError(Platform: core)[DraggableDirective -> DraggableHelper]:
NullInjectorError: No provider for DraggableHelper!
at NullInjector.get (core.js:1002)
at resolveToken (core.js:1300)
at tryResolveToken (core.js:1242)
at StaticInjector.get (core.js:1110)
at resolveToken (core.js:1300)
at tryResolveToken (core.js:1242)
at StaticInjector.get (core.js:1110)
at resolveNgModuleDep (core.js:10854)
at NgModuleRef.get (core.js:12087)
at resolveDep (core.js:12577)

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:5.2.0
- `angular-draggable-droppable`:1.0.1
- Browser name and version:
Google Chrome 68.0.3440.106 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
It sounds like you're not calling the `DragAndDropModule.forRoot()` method, happy to debug more if you can attach a minimal repro. Thanks!

**Comment by sumansjs** [comment]
Hey @2easy2pay ,
Did your problem got fixed ? I am also encountering the same problem on deployment. My --prod flag code has been built successfully

Hi @mattlewis92 ,
Even after adding the DragAndDrop Module in the main module and using DragAndDropModule.forRoot(), the problem in not fixed.
