### ISSUE TITLE
Is there anyway to bind the mwlDraggable ?

### ISSUE THREAD

**Issue by daneshmandi** [mattlewis92/angular-draggable-droppable#64]
**Is your feature request related to a problem? Please describe**

I need to dynamically set whether an item can be dragged or not. 

**Describe the solution you'd like**

I would like to be able to bind mwlDraggable like [mwlDraggable]="ConditionBooleanFlag" ?

**Describe your use case for implementing this feature**

I have a list dynamic list that I would like to enable or disable mwlDraggable on each list item based on certain condition.

**Additional context**

**Comment by daneshmandi** [comment]
It seems there is a way to achieve this using dragAxis input of mwlDraggable.

Like:
`[dragAxis]="{x:DragEnabled,y:DragEnabled}"`

**Comment by mattlewis92** [comment]
You got it, the `dragAxis` is how to control what can be dragged. You can see an example of it in the wild [here](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts#L132)
