### ISSUE TITLE
How can we set drag delta threshold to some certain value? 

### ISSUE THREAD

**Issue by daneshmandi** [mattlewis92/angular-draggable-droppable#65]
**Is your feature request related to a problem? Please describe**

I see the drop event fires when even the mouse has not moved much to be considered a drag has happened first. Sometime very sensitive mouses move slightly on mouse click which in this case it will be considered as drop. This would cause a problem for me as in my app I have a concept of selection and drag at the same time.

**Describe the solution you'd like**

Being able to inject custom drag threshold to the directive as input.

**Describe your use case for implementing this feature**

@Input() dragXThreshold:number;
@Input() dragXThreshold:number;

as DraggableDirective or DroppableDirective

**Comment by daneshmandi** [comment]
It seems that there is a way to do this using validateDrag input of mwlDraggable.

[validateDrag]="CanDrag"

`CanDrag(coordinates: { x: number, y: number }): boolean
  {
    return Math.abs(coordinates.x) > 10 || Math.abs(coordinates.y) > 10;
  }`

[I have post this as it may help someone else] :)

**Comment by mattlewis92** [comment]
That's right! There's an example of it in the wild [here](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/week/calendar-week-view.component.ts#L137)
