### ISSUE TITLE
dragCursor not working 

### ISSUE THREAD

**Issue by AhmedLoud** [mattlewis92/angular-draggable-droppable#67]
I am trying to change the cursor style when dragging and I can't. 
I tried using the dragCursor attribute as an input 

```
  <div
    class="drag-icon"
    mwlDraggable
    class="drag-icon"
    dragCursor="not-allowed"
    dragActiveClass="drag-active"
    (dragging)="onDragging($event)"
    (dragEnd)="onDragEnd($event)"></div>
```

**Versions**

- `@angular/core`: 6.0.4
- `angular-draggable-droppable`: 4.0.2
- Browser name and version: Chrome/61.0.3163.100

**Comment by George35mk** [comment]
@AhmedLoud  make sure you have look at this example, don't forget the CSS file
https://github.com/mattlewis92/angular-draggable-droppable/tree/master/src/demo

**Comment by mattlewis92** [comment]
It's [working for me](https://stackblitz.com/edit/angular-2u6w2b?file=src%2Fapp%2Fapp.component.html), if you're still getting issues please make a minimal repro that shows your issue, thanks! 😄
