### ISSUE TITLE
Restrict dragging within parent container

### ISSUE THREAD

**Issue by coder123456** [mattlewis92/angular-draggable-droppable#77]
**Is your feature request related to a problem? Please describe**
Help request

**Describe the solution you'd like**
I am looking for a way to restrict dragging a div with the parent div container. If you could provide an example would be of great help.

**Describe your use case for implementing this feature**
Restrict dragging within parent container

**Additional context**
None

**Comment by mattlewis92** [comment]
If you do the transformation of the dragged element yourself, you can adjust it so it's constrained within a container. I put together an example of this here for you: https://stackblitz.com/edit/angular-mbwxql?file=src/app/app.component.ts Hope that helps! 😄
