### ISSUE TITLE
Add long touch feature inside scroll container

### ISSUE THREAD

**Issue by Onyphlax** [mattlewis92/angular-draggable-droppable#78]
**Is your feature request related to a problem? Please describe**

Hi, I'm using your plugin in a scroll container but i should be able to scroll the container with a touch.
However the touch drag an item and scroll the container.

**Describe the solution you'd like**

As a previous issue, there is a solution like a drag handle. But for my case i want to use a long touch and then be able to drag the item without scrolling the container. 
For example you begin the touch and after like 300ms you can drag the item, otherwise you scroll the container.

**Additional context**

I've already fork the project and add this feature with tests in local.

**Comment by mattlewis92** [comment]
That sounds like a great feature, please send a PR! 😄

**Comment by artem-galas** [comment]
I've found one little bug related to this feature.

If you wrap you `mwlDraggable` element to `<ng-template>` it doesn't work

I've created the stackbliz example for it
https://stackblitz.com/edit/angular-zktmrw

I'm not sure how to solve it.
