### ISSUE TITLE
Prevent mobile device to scroll body when dragging item

### ISSUE THREAD

**Issue by Onyphlax** [mattlewis92/angular-draggable-droppable#80]
**Describe the bug**

Hi again, I was testing the demo on an Android and iOS and it was really painful.

On an Android phone, your demo has a scroll so when you drag an item it's also scrolling the container.
On an Android tablet, there is no scroll but if you drag too far to the bottom the reload button appears (same on phone).
And on an iOS device even if there is no scroll, the entire page will drag.

A working solution i tried is to add a `event.preventDefault()` at the beginning of the `onTouchStart` function in draggable directive.

**Comment by mattlewis92** [comment]
Looks like this is fixed by https://github.com/mattlewis92/angular-draggable-droppable/pull/79 as well 👍
