### ISSUE TITLE
Position of mouse cursor / pointer on Ghost element

### ISSUE THREAD

**Issue by rile81** [mattlewis92/angular-draggable-droppable#81]
**Is your feature request related to a problem? Please describe**

I have the following problem: When the ghost element of a draggable is smaller than the draggable itself, it can cause an undesirable effect. When dragging from the left of the draggable everything is fine but when dragging from the right, the mouse cursor / pointer is far apart from the ghost element:

<img src="https://i.ibb.co/WHTgt7d/Drag-Drop-Issue.png"/>

**Describe the solution you'd like**

I've tried using this example [https://stackblitz.com/edit/angular-mbwxql?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-mbwxql?file=src%2Fapp%2Fapp.component.ts), but it references the HTMLElement of the draggable itself instead of a ghost template. I've tried referencing the TemplateRef with no success. Could you help me?

**Describe your use case for implementing this feature**

A clear interface for the user and no undesired effects.

**Additional context**

None

**Comment by mattlewis92** [comment]
Hey, so sorry about the late reply on this one, are you still having trouble with it? Would you be able to put together a minimal stackblitz example that shows the issue you're experiencing? Thank you! 😄

**Comment by rile81** [comment]
Hi Matt,

Thank you for your reply.
I've put together a minimal stackblitz to explain the issue:
[https://stackblitz.com/edit/angular-p7scvt](https://stackblitz.com/edit/angular-p7scvt)

It's a draggable element with a smaller ghost template.
When you start dragging from the left side, everything looks fine.
When you start dragging from the right side, the mouse cursor is not on top of the ghost element.

Is there any way to position the ghost element (like a transform) when you start dragging?
Thank you for your time!

**Comment by mattlewis92** [comment]
Ahh, I see it now, thanks so much for taking the time to make a repro, will see what I can come up with 😄

**Comment by mattlewis92** [comment]
If you update to `4.2.0` I've just added some extra details to the ghostElementCreated event so you can fix this yourself. I've updated your demo to show you how here: https://stackblitz.com/edit/angular-mdrd8e?file=src/app/app.component.ts Hope that helps! 😄

**Comment by rile81** [comment]
Awesome, thanks Matt! 😄
