### ISSUE TITLE
Start Drag On Click

### ISSUE THREAD

**Issue by laijuthomas** [mattlewis92/angular-draggable-droppable#84]
**Is your feature request related to a problem? Please describe**

No

**Describe the solution you'd like**

When user click on a draggable element I want to start the dragging.

**Describe your use case for implementing this feature**

Start dragging on click

**Additional context**

**Comment by mattlewis92** [comment]
You can use the [`dragPointerDown`](https://mattlewis92.github.io/angular-draggable-droppable/docs/directives/DraggableDirective.html#dragPointerDown) event instead of `dragStart` to hook into this event. Hope that helps! 😄
