### ISSUE TITLE
Apply css style to ghost element when entering drop zone

### ISSUE THREAD

**Issue by torbgy** [mattlewis92/angular-draggable-droppable#85]
**Describe the bug**
Updating CSS style of ghost element when entering drop zone won't work.
Console shows that it updates the variables, but it is not shown visually.

**Minimal reproduction of the problem with instructions**

in html:
```
<div [attr.id]="subkey"
    class="drag-item"
    mwlDraggable
    dropData={{subkey}}  
    dragActiveClass="ghost-drag" 
    [ghostDragEnabled]="true"
    [showOriginalElementWhileDragging] ="true"
                
    [ghostElementAppendTo] ="body"
    [dragSnapGrid]="snapping"
    (dragging)="this.dragging($event)">
    <img src={{subcomp.icon}}/>
</div>
```

in CSS:
```
.ghost-drag {
  background: white;
  border: 1px solid #CCC;
  width:50px;
  height:40px;
}
```

In component.ts:
```
dragging({ x, y }) {
    this.snapping = this.dragservice.getSnap();
    let values = Object.keys(this.snapping).map(key => this.snapping[key]);//.map(key => this.snapping[key]);
    //console.log(;
    this.transform.x = x - 150;
    this.transform.y = y;
    this.dragservice.setCoor(this.transform.x, this.transform.y);
    if(values[0] == 20){
      let element = document.getElementById("Resistor");
      element.setAttribute("style", "width:120px, height:40px");
      console.log(element);
    }
    else{
      let element = document.getElementsByClassName('drag-item');
      element[0].setAttribute("style", "width:50px, height:40px;")
    }
    //console.log('x:' + x + ' y:' + y);
  }
```

**Screenshots**
![test](https://user-images.githubusercontent.com/10559455/53698486-bd081100-3ddd-11e9-9787-112acb928514.png)

**Versions**

- `@angular/core`: "~7.2.0"
- `angular-draggable-droppable`: "^4.0.0-beta.18"
- Chrome 72.0.3626.119 (64-bit)

**Comment by mattlewis92** [comment]
Unfortunately this is a limitation with the implementation of this lib, as it uses [cloneNode](https://github.com/mattlewis92/angular-draggable-droppable/blob/master/projects/angular-draggable-droppable/src/lib/draggable.directive.ts#L353-L355) to make the ghost element. So any changes you make to the host element won't be reflected in the ghost element. What about if I exposed the ghost dom element in the [`ghostElementCreated`](https://github.com/mattlewis92/angular-draggable-droppable/blob/master/projects/angular-draggable-droppable/src/lib/draggable.directive.ts#L401) hook and then you could add the styles to the ghost element as you saw fit, would that work for you?

**Comment by torbgy** [comment]
That could work!

I think having a way to change the ghost element, e.g. When the ghost element enters the drop zone, it can be resized or color change.

**Comment by mattlewis92** [comment]
Added in `4.2.0`! 😄
