### ISSUE TITLE
Change the cursor on draggable elements on hover

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-draggable-droppable#9]

**Comment by jose-torres-marin** [comment]
Is there any way to not do this? I've got items that are supposed to be clickable AND draggable, so I'd like to retain the pointer cursor and change it only on "dragging", not on hover.

Thanks

**Comment by mattlewis92** [comment]
Good idea! You can now do this in `1.1.0` by setting `dragCursor=""` on the draggable element 😄

**Comment by jose-torres-marin** [comment]
Superb, thanks a lot for the change!
