### ISSUE TITLE
Warning: 'ɵɵdefineInjectable' was not found in '@angular/core'  on 4.3.3

### ISSUE THREAD

**Issue by davidzxc12** [mattlewis92/angular-draggable-droppable#97]
Is the version 4.3.3 compatible with angular 6 ?

I use angular-calendar in my angular 6 project, and it update angular-draggable-droppable version from 4.3.2 -> 4.3.3.

And then I recieved the warning and it leads to crash
`WARNING in ./node_modules/angular-draggable-droppable/fesm5/angular-draggable-droppable.js 33:57-75
"export 'ɵɵdefineInjectable' was not found in '@angular/core'`

Is there some fix? 

many thanks.

**Comment by mattlewis92** [comment]
Sorry about that! I just pushed `4.3.4` with a fix
